name: nicolette
description: "Intelligent workforce scheduling application for managing assignment rotations, worker equity, and time-off management."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database and Storage
  sqflite: ^2.3.0              # SQLite database for local storage
  sqflite_common_ffi: ^2.3.0   # SQLite FFI for desktop platforms
  path: ^1.9.0                 # File path utilities for database
  
  # State Management
  provider: ^6.1.1             # State management solution
  
  # Navigation
  go_router: ^12.1.3           # Declarative routing
  
  # UI Components
  cupertino_icons: ^1.0.6      # iOS style icons
  
  # Date and Time
  intl: ^0.19.0                # Internationalization and date formatting
  
  # Utilities
  equatable: ^2.0.5            # Value equality
  
  # File Operations
  path_provider: ^2.1.2        # Get application directories

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0        # Linting rules

flutter:
  uses-material-design: true